FROM golang:1.24.4-alpine3.22 AS builder

RUN mkdir /assets

ENV STATIC_FILES=/assets

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go build -o main .

ENTRYPOINT [ "./main" ]