FROM golang:1.18.0-alpine3.15 as builder

RUN mkdir /assets

ENV STATIC_FILES=/assets

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go build -o main .

ENTRYPOINT [ "./main" ]